package bg.finance.models;

import javax.persistence.*;

@Entity
public class Expense {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    //Setting the id to 0, so it will be autogenerated by mySql
    private int id = 0;
    private int user;
    private String name;
    private double amount;
    private int date;
    private int category;
    private int timestamp;
    private int clientsideId;


    public Expense(String name, double amount, int date, int category, int user, int timestamp, int clientsideId) {
        this.name = name;
        this.amount = amount;
        this.date = date;
        this.category = category;
        this.user = user;
        this.timestamp = timestamp;
        this.clientsideId = clientsideId;
    }

    public int getClientsideId() {
        return clientsideId;
    }

    public void setClientsideId(int clientsideId) {
        this.clientsideId = clientsideId;
    }

    public Expense(){}


    public int getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(int timestamp) {
        this.timestamp = timestamp;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUser() {
        return user;
    }

    public void setUser(int user) {
        this.user = user;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public int getDate() {
        return date;
    }

    public void setDate(int date) {
        this.date = date;
    }

    public int getCategory() {
        return category;
    }

    public void setCategory(int category) {
        this.category = category;
    }
}
